# Generated by Django 4.2 on 2023-06-24 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryman',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.deliveryman'),
        ),
    ]
